wc -l lab0/shelmet2 >> lab0/shelmet02;
echo "-----------------";
ls -liR lab0 | grep '^m' | sort -k1,1n | head -n 3;
echo "-----------------";
ls  2> /dev/null -R lab0 | grep '2$' | sort -d;
echo "-----------------";
ls -lt 2> /dev/null -lRt lab0 | grep -E 'do' | sort -k6,8 | head -n 4;
echo "-----------------";
ls -lRr lab0 | grep 'k$' | sort -d;
echo "-----------------";
ls -lRt lab0 | grep ' m' | sort -k6,8 | head -n 4;