DROP TABLE LOCATION CASCADE;
DROP TABLE DINOSAURS CASCADE;
DROP TABLE PEOPLE CASCADE;
DROP TABLE WORKER CASCADE;
DROP TABLE WORK CASCADE;
DROP TABLE MARKER CASCADE;
DROP TABLE WORK_OBJECT CASCADE;
DROP TABLE WORK_MARKER;