CREATE TYPE GENDER AS ENUM ('М', 'Ж');
CREATE TYPE COLOR AS ENUM ('ЗЕЛЕНЫЙ', 'КРАСНЫЙ');
CREATE TYPE TYPE AS ENUM ('ДИЛОФОЗАВР', 'ТИРАНОЗАВР');

CREATE TABLE LOCATION (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
IS_NEAR_RIVER BOOLEAN DEFAULT FALSE
);

CREATE TABLE PEOPLE (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
GENDER GENDER,
IS_HAPPY BOOLEAN DEFAULT TRUE
);

CREATE TABLE WORKER (
ID SERIAL PRIMARY KEY,
PERSON_ID INT REFERENCES PEOPLE(ID),
FUNCTION VARCHAR(100)
);

CREATE TABLE WORK_OBJECT (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(100)
);

CREATE TABLE MARKER (
ID SERIAL PRIMARY KEY,
COLOR COLOR,
PURPOSE VARCHAR(100),
PLACED_BY_ID INT REFERENCES WORKER(ID),
OBJECT_ID INT REFERENCES WORK_OBJECT(ID)
);

CREATE TABLE WORK (
ID SERIAL PRIMARY KEY,
ACTION VARCHAR(100),
LENGTH INT,
SUBJECT_ID INT REFERENCES WORKER(ID),
OBJECT_ID INT REFERENCES WORK_OBJECT(ID),
MARKER_ID INT REFERENCES MARKER(ID)
);

CREATE TABLE DINOSAURUS (
ID SERIAL PRIMARY KEY,
TYPE TYPE,
LOCATION_ID INT REFERENCES LOCATION(ID)
);