/*
SELECT PEOPLE.NAME, WORK.ACTION, WORK_OBJECT.NAME, LOCATION.NAME, DINOSAURUS.LOCATION_ID = WORK.LOCATION_ID AS WORK_NEAR_DINO FROM PEOPLE
JOIN WORKER on WORKER.PERSON_ID = PEOPLE.ID
JOIN WORK ON WORK.WORKER_ID = WORKER.ID
JOIN WORK_OBJECT ON WORK.OBJECT_ID = WORK_OBJECT.ID
JOIN LOCATION ON WORK.LOCATION_ID = LOCATION.ID
LEFT JOIN DINOSAURUS ON LOCATION.ID = DINOSAURUS.LOCATION_ID
ORDER BY PEOPLE.NAME;
*/ -- ПОЛУЧИТЬ ВСЮ РАБОТУ
WITH PERSON_COUNTS AS(
SELECT PEOPLE.NAME, COUNT(DISTINCT WORK_OBJECT.ID) AS AMOUNT FROM PEOPLE
JOIN WORKER on WORKER.PERSON_ID = PEOPLE.ID
JOIN WORK ON WORK.WORKER_ID = WORKER.ID
JOIN WORK_OBJECT ON WORK.OBJECT_ID = WORK_OBJECT.ID
JOIN LOCATION ON WORK.LOCATION_ID = LOCATION.ID
JOIN DINOSAURUS ON LOCATION.ID = DINOSAURUS.LOCATION_ID
JOIN MARKER ON MARKER.WORK_OBJECT_ID = WORK_OBJECT.ID
WHERE DINOSAURUS.LOCATION_ID = WORK.LOCATION_ID AND WORK_OBJECT.ID = MARKER.WORK_OBJECT_ID AND WORK.ACTION = 'поставить'
GROUP BY PEOPLE.NAME) 
SELECT NAME, AMOUNT FROM PERSON_COUNTS
WHERE AMOUNT = (SELECT MAX(AMOUNT) FROM PERSON_COUNTS); -- ВОЗВРАЩАЕТ ИМЯ И КОЛИЧЕСТВО МАРКЕРОВ, УСТАНОВЛЕННЫХ В ЛОКАЦИИ С ДИНОЗАВРАМИ
